---
- name: "Get Security ID"
  ansible.builtin.uri:
    url: "{{ apstra.baseurl }}/blueprints/{{ bp_id }}/diff"
    method: GET
    return_content: yes
    status_code: 200
    headers:
      content-type: "application/json"
      AUTHTOKEN: "{{ login.json.token }}"
    validate_certs: false
    force_basic_auth: yes
  register: security

- name:
  debug:
    msg: "{{ security.json }}"

- name: Filter non-null values
  set_fact:
    filtered_output: "{{ security.json | dict2items }}"


- debug:
    var: filtered_output

- name: Filter items with non-null value
  set_fact:
    non_null: "{{ filtered_output | json_query('[?value != `null`].key') }}"

- name:
  set_fact:
    digest: "{{ security.json.digest }}"

- name:
  debug:
    var: digest

- name:
  set_fact:
    is_there_a_commit: true
  when: 
    digest.node.added > 0 or
    digest.node.changed > 0 or
    digest.node.removed > 0 or
    digest.relationship.added > 0 or
    digest.relationship.changed > 0 or
    digest.relationship.removed > 0

- name:
  set_fact:
    is_there_a_commit: false
  when: 
    digest.node.added == 0 and
    digest.node.changed == 0 and
    digest.node.removed == 0 and
    digest.relationship.added == 0 and
    digest.relationship.changed == 0 and
    digest.relationship.removed == 0

- name:
  debug:
    var: is_there_a_commit
