---
  ### ---------------------------------------------------------------------------
  ### APSTRA API AUTOMATION
  ### ---------------------------------------------------------------------------
  - hosts: localhost
    gather_facts: True
    connection: local
    roles:
      - { role: apstra_auth }

    tasks:
      - name: "Get Blueprint ID"
        ansible.builtin.uri:
          url: "{{ apstra.baseurl }}/blueprints"
          method: GET
         # return_content: yes
          status_code: 200
          headers:
            content-type: "application/json"
            AUTHTOKEN: "{{ login.json.token }}"
          validate_certs: false
          force_basic_auth: yes
        register: bp_ids

      - name: Get current date and time
        command: python3 -c 'import datetime; now = datetime.datetime.now(); print(now.strftime("%Y-%m-%d %H:%M:%S.%f"))'
        register: current_datetime

      - name: Print current date and time with timezone offset
        debug:
          msg: "{{ current_datetime.stdout }}+03:00"

      - name: Retrieve Blueprint ID
        ansible.builtin.set_fact:
          bp_id: "{{ bp_ids.json | cleanup_bp_id(bp_name) }}"

      - name: set timedate to get consistency accross the collected data
        ansible.builtin.set_fact:
          datetime_of_pb: "{{ ansible_date_time['iso8601_basic'] }}"



      - name: Get dcn_routingzone table from PostgreSQL
        postgresql_query:
          db: "{{ pg_login_db }}"
          login_user: "{{ pg_login_user }}"
          login_password: "{{ pg_login_password }}"
          login_host: "{{ pg_login_host }}"
          query: SELECT (name, blueprint_id, remote_id) FROM {{ sz_tablename }}
        register: szs_table

      - name: show rz_table
        ansible.builtin.set_fact:
          szs_bp_rmids: "{{ szs_table.query_result | unique | select | list }}"




      
      - name: show rz_table consolidated
        ansible.builtin.debug:
          msg: "{{ szs_bp_rmids }}"        




      - name: Get security zones from apstra
        ansible.builtin.uri:
          url: "{{ apstra.baseurl }}/blueprints/{{ bp_id }}/nodes?node_type=security_zone"
          method: GET
          return_content: yes
          status_code: 200
          headers:
            content-type: "application/json"
            AUTHTOKEN: "{{ login.json.token }}"
          validate_certs: false
          force_basic_auth: yes
          body_format: json
        register: szs


      - name: show security zones apstra structured data
        ansible.builtin.set_fact:
          nodes: "{{ szs.json['nodes'] }}"


      - name: show presql data
        ansible.builtin.debug:
          var: nodes

      - name: Print label and id
        debug:
          msg: "{{ item.value.label }}, {{ bp_id }}, {{ item.value.id }}"
        loop: "{{ nodes | dict2items }}"

      - name: Set label, bp_id, and id as a fact
        set_fact:
          id: "{{ nodes | dict2items | map(attribute='value.id') | list }}"

      - name:
        debug:
          var: id

      - name: Set label, bp_id, and id as a fact
        set_fact:
          label: "{{ nodes | dict2items | map(attribute='value.label') | list }}"

      - name:
        debug:
          var: label

      - name: Extract label and id from nodes
        set_fact:
          concatenated_list: "{{ concatenated_list | default([]) + [item.value.label ~ ', ' ~ item.key] }}"
        loop: "{{ nodes | dict2items }}"
        loop_control:
          label: "{{ item.value.id }}"

      - name: Display concatenated list
        debug:
          msg: "{{ concatenated_list }}"

      - name: set systems_info to seed postgresql template file
        ansible.builtin.set_fact:
          szs_info: "{{ szs.json['nodes'] |  get_seczones_pgsql_ready_format(bp_id, szs_bp_rmids) }}"

      - name: set timedate to get consistency accross the collected data
        ansible.builtin.set_fact:
          datetime_of_pb: "{{ ansible_date_time['iso8601_basic'] }}"

      - name: Delete routing zones that does not exist in apstra but postgresql
        postgresql_query:
          db: "{{ pg_login_db }}"
          login_user: "{{ pg_login_user }}"
          login_password: "{{ pg_login_password }}"
          login_host: "{{ pg_login_host }}"
          query: "{{ lookup('ansible.builtin.template', './templates/pgsql-q-insert-seczones-kutay.j2') }}"

