---
- name: Set is_vn_id_in_nodes_fw
  set_fact:
    is_vn_id_in_nodes_fw: false

- name: Search VN From CT
  ansible.builtin.include_role:
    name: search_vn_from_ct

- name: Search VN From FW-CT
  ansible.builtin.include_role:
    name: search_vn_from_fw_ct
  when: item.is_gateway_type_fw == true

- name:
  debug:
    var: is_vn_id_in_nodes

- name:
  debug:
    var: is_vn_id_in_nodes_fw

- name: Add VN to CT
  ansible.builtin.include_role:
    name: add_vn_to_ct_multiple
  when: is_vn_id_in_nodes == false

- name: Add VN to FW-CT
  ansible.builtin.include_role:
    name: add_vn_to_fw_ct_multiple
  when: is_vn_id_in_nodes_fw == false and item.is_shared_vn == false and item.is_gateway_type_fw == true
