---
- name: Add VN to CT
  ansible.builtin.include_role:
    name: search_vn_from_ct

- name: Add VN to CT
  ansible.builtin.include_role:
    name: search_vn_from_fw_ct
  when: item.is_gateway_type_fw == true

- name: Add VN to CT
  ansible.builtin.include_role:
    name: add_vn_to_ct_multiple
  when: is_vn_id_in_nodes == false

- name: Add VN to FWCT
  ansible.builtin.include_role:
    name: add_vn_to_fw_ct_multiple
  when: is_vn_id_in_nodes_fw == false and item.is_shared_vn == false and item.is_gateway_type_fw == true
