### ---------------------------------------------------------------------------
### GET BLUEPRINT ID
### ---------------------------------------------------------------------------
- name: "Get Blueprint ID"
  uri:
    url: "{{ apstra.baseurl }}/blueprints"
    method: GET
   # return_content: yes
    status_code: 200
    headers:
      content-type: "application/json"
      AUTHTOKEN: "{{ login.json.token }}"
    validate_certs: false
    force_basic_auth: yes
  register: bp_ids

- name: Retrieve Blueprint ID
  set_fact: 
    bp_id: "{{ bp_ids.json | cleanup_bp_id(bp_name) }}"

- name:
  ansible.builtin.debug:
    msg: "{{ bp_id }}"

- name: "Check if bp_id is empty"
  fail:
    msg: "HATA: İlgili Apstra üzerinde {{bp_name}} isimli Blueprint bulunmamaktadır."
  when: bp_id is not defined or bp_id | length == 0

