### ---------------------------------------------------------------------------
### GET BLUEPRINT ID
### ---------------------------------------------------------------------------
- name: "Get Blueprint ID"
  uri:
    url: "{{ apstra.baseurl }}/blueprints"
    method: GET
   # return_content: yes
    status_code: 200
    headers:
      content-type: "application/json"
      AUTHTOKEN: "{{ login.json.token }}"
    validate_certs: false
    force_basic_auth: yes
  register: bp_ids

- name:
  debug:
    var: bp_ids

- name:
  set_fact:
    bp_id: "{{ bp_ids.json['items'][0].id }}"

- name:
  ansible.builtin.debug:
    msg: "{{ bp_id }}"
