---
#apstra:
#  username: "admin"
#  password: "S3kom123!"
#  baseurl: "https://10.106.20.29/api"
#bp_name: "ISA-BP"          ### Blueprint name

  
sz:
  name: DC_VRF
  vns:
    - vlan_id: 200
      name: VLAN200
bp_name: TBLUEPRINT
ct_name: ABC-TEST-CT-1
vn_name: ILO_10_25_104_3_24
apstra:
  baseurl: 'https://10.106.32.3/api'
  username: admin
  password: q1w2e3r4Q!W@Q!W@
pg_login_db: "dcnetwork"
pg_login_user: "dcnetwork"
pg_login_password: "q1w2e3r4"
pg_login_host: "10.106.20.122"
