---
sz:
  name: DC_VRF
  vns:
    - name: OCP-LAB-TEST4_10_98_13_33_28
      vn_id: 50234
      ct_name: vsphere
      vlan_id: 234
      fw_ct_name: firewall-int
      is_external: false
      is_heartbeat: false
      is_shared_vn: false
      is_current_vn: true
      is_gateway_type_fw: false
bp_name: TBLUEPRINT
apstra:
  baseurl: 'https://10.106.32.3/api'
  username: telemetry
  password: S3kom123!
pg_login_host: 10.106.80.230
pg_login_db: dcnetwork
pg_login_user: dcnetwork
pg_login_password: q1w2e3r4
