---
- name: "Get Security ID"
  ansible.builtin.uri:
    url: "{{ apstra.baseurl }}/blueprints/{{ bp_id }}/virtual-networks"
    method: GET
    return_content: yes
    status_code: 200
    headers:
      content-type: "application/json"
      AUTHTOKEN: "{{ login.json.token }}"
    validate_certs: false
    force_basic_auth: yes
  register: virtual_networks

- name:
  debug:
    msg: "{{ virtual_networks.json.virtual_networks }}"
  register: virtual_networks

    #- name:
    #  debug:
    #    var: virtual_networks

- name: Extract labels
  set_fact:
    labels: "{{ virtual_networks.msg | dict2items }}"

- name:
  ansible.builtin.set_fact:
    vn_name: "{{ vn.name }}"

      #- name: Print labels
      #  debug:
      #    msg: "{{ labels }}"

- name: Find ID for label "TVNI-112-101"
  set_fact:
    desired_vn_id: "{{ labels | selectattr('value.label', 'equalto', vn_name) | map(attribute='value.id') }}"

      #- name: Print the ID
      #  debug:
      #    msg: "ID for label {{ vn_name }} is: {{ desired_vn_id }}"

- name: "Get Connectvity Template"
  uri:
    url: "{{ apstra.baseurl }}/blueprints/{{ bp_id }}/obj-policy-export"
    method: GET
    status_code: 200
    headers:
      content-type: "application/json"
      AUTHTOKEN: "{{ login.json.token }}"
    validate_certs: false
    force_basic_auth: yes
      #body: "{{ lookup('ansible.builtin.template','templates/connectivity-template.j2') }}"
    body_format: json
  ignore_errors: yes
  register: cts

- name:
  ansible.builtin.set_fact:
    fw_ct_name: "{{ vn.fw_ct_name }}"

- name:
  ansible.builtin.set_fact:
    vn_id: "{{ vn.vn_id }}"

- name:
  ansible.builtin.set_fact:
    vlan_id: "{{ vn.vlan_id }}"

- name:
  ansible.builtin.set_fact:
    name: "{{ vn.name }}"

- name: Retrieve Blueprint ID
  ansible.builtin.set_fact:
    desired_id: "{{ cts.json.policies | selectattr('label', 'search', fw_ct_name) | map(attribute='id') | first }}"

- name: show blueprint id
  ansible.builtin.debug:
    msg: "{{ desired_id }}"

- name: "Get Connectvity Template"
  uri:
    url: "{{ apstra.baseurl }}/blueprints/{{ bp_id }}/obj-policy-export/{{ desired_id }}"
    method: GET
    status_code: 200
    headers:
      content-type: "application/json"
      AUTHTOKEN: "{{ login.json.token }}"
    validate_certs: false
    force_basic_auth: yes
      #body: "{{ lookup('ansible.builtin.template','templates/connectivity-template.j2') }}"
    body_format: json
  ignore_errors: yes
  register: ct_j2

- name: Retrieve Blueprint IDs22
  ansible.builtin.set_fact:
    ctt_j2: "{{ ct_j2.json }}"

      #- name:
      #  debug:
      #    var: ctt_j2

- name:
  ansible.builtin.set_fact:
    attach_node_ids: "{{ ct_j2.json.policies | json_query('[?policy_type_name==`AttachMultipleVLAN`].attributes.tagged_vn_node_ids') | first }}"

      #- name:
      #  debug:
      #    var: attach_node_ids
      #- name:
      #  debug:
      #    var: attach_node_ids

      #- name:
      #  debug:
      #    var: desired_vn_id

- name: Extract the first item from desired_vn_id list
  set_fact:
    first_vn_id: "{{ desired_vn_id[0] }}"

- name: Check if first_vn_id is in attach_node_ids
  set_fact:
    is_vn_id_in_nodes_fw: "{{ first_vn_id in attach_node_ids }}"

      #- name: Debug output
      #  debug:
      #    msg: "first_vn_id is in attach_node_ids: {{ is_vn_id_in_nodes_fw }}"
